#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# PHP Debugger (xdebug|blackfire|none)

PHP_DEBUGGER=xdebug

#######################################
# Context environment

# TYPO3
TYPO3_CONTEXT=Development/Docker

# Symfony
SYMFONY_ENV=dev
SYMFONY_DEBUG=0

  # CakePHP
CAKE_ENV=dev

  # yii
YII_ENVIRONMENT=Development

  #laravel
APP_NAME=MAMIAS
APP_ENV=local
APP_DEBUG=true
APP_URL=http://mamias.docker.localhost:8000
